development:
  store: innobuz-com.myshopify.com
  password: c317c5ec1fa00a7caf0632723c31c198
  theme_id: "47762997302"
  bucket_size: 40
  refill_rate: 2
  ignore_files:
    - "x*.swp"
    - "*~"
    - "config/settings_data.json"